"""Changes to contribution model

Revision ID: 3e1dba57e994
Revises: 4820c9c3c7d4
Create Date: 2025-07-01 09:57:10.856722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1dba57e994'
down_revision = '4820c9c3c7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_development_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'staff_development_needs', ['need_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_development_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
