"""alters

Revision ID: 450930f3d176
Revises: d309cce9a5b1
Create Date: 2025-06-19 15:40:38.218107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '450930f3d176'
down_revision = 'd309cce9a5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_assets', schema=None) as batch_op:
        batch_op.alter_column('last_maintenance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_assets', schema=None) as batch_op:
        batch_op.alter_column('last_maintenance',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
