"""Add FK to water_test

Revision ID: 4820c9c3c7d4
Revises: 9867cc5a26d9
Create Date: 2025-06-30 03:48:24.973878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4820c9c3c7d4'
down_revision = '9867cc5a26d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_quality_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('water_quality_tests_test_type_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'water_quality_test_types', ['test_type_id'], ['id'])
        batch_op.drop_column('test_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_quality_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('water_quality_tests_test_type_fkey', 'water_quality_test_types', ['test_type'], ['id'])
        batch_op.drop_column('test_type_id')

    # ### end Alembic commands ###
