"""Adds columns to staff records

Revision ID: a8bbfaca7ad8
Revises: ca9730d9e180
Create Date: 2025-07-08 14:45:00.026973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bbfaca7ad8'
down_revision = 'ca9730d9e180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_development_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_met', sa.Boolean(), nullable=False, server_default=sa.false()))

        batch_op.add_column(sa.Column('date_met', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_development_records', schema=None) as batch_op:
        batch_op.drop_column('date_met')
        batch_op.drop_column('is_met')

    # ### end Alembic commands ###
